/// <reference path="../types.d.ts" />
// AUTO-GENERATED by scripts/build-tws-hooks.mjs — 唔好手改
// 部署 NAS：複製 tws_routes.pb.js + tws.pb.js 去 pb_data/pb_hooks/

var twsUserAuthMiddleware = (function() {
  try {
    if (typeof $apis !== "undefined" && $apis && typeof $apis.requireAuth === "function") {
      return $apis.requireAuth("users");
    }
  } catch (errA) {}
  try {
    if (typeof $apis !== "undefined" && $apis && typeof $apis.requireRecordAuth === "function") {
      try { return $apis.requireRecordAuth("users"); } catch (errR1) {}
      return $apis.requireRecordAuth();
    }
  } catch (errB) {}
  return function(e) { try { if (e && typeof e.next === "function") e.next(); } catch (errC) {} };
})();

routerAdd("GET", "/tws/health", function(e) {
  return e.json(200, { ok: true, service: "tws", version: 31, rbac: "tenant_members", pb_compat: true, debug: "/tws/debug-auth" });
});

routerAdd("GET", "/tws/debug-auth", function(e) {

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };

  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var auth = e.auth;
  if (!auth) {
    try {
      var info = $apis.requestInfo(e);
      if (info && info.authRecord) auth = info.authRecord;
    } catch (err) {}
  }
  var uid = auth ? String(auth.id || "") : "";
  var memberships = [];
  var probe = {
    hasAppFindRecordsByFilter: typeof $app.findRecordsByFilter === "function",
    hasDaoFindFirstRecordByData: !!(function() {
      try { return $app.dao() && typeof $app.dao().findFirstRecordByData === "function"; } catch (e) { return false; }
    })(),
  };
  if (uid) {
    try {
      var rows = queryRecords("tenant_members", "user_id = {:uid}", 50, { uid: uid });
      if (!rows.length) {
        var direct = findByField("tenant_members", "user_id", uid);
        if (direct) rows = [direct];
      }
      for (var i = 0; i < rows.length; i++) {
        memberships.push({
          tenant_id: recordStr(rows[i], "tenant_id"),
          role: normalizeMemberRole(recordStr(rows[i], "role")),
        });
      }
      probe.memberQueryCount = rows.length;
    } catch (err3) {
      probe.error = String(err3 && err3.message ? err3.message : err3);
    }
  }
  var owned = [];
  for (var oi = 0; oi < memberships.length; oi++) {
    if (memberships[oi].role === "owner") owned.push(memberships[oi]);
  }
  var isAdmin = false;
  if (auth) {
    try { isAdmin = auth.getBool("is_platform_admin") === true; } catch (e1) {
      try { isAdmin = auth.get("is_platform_admin") === true; } catch (e2) { isAdmin = false; }
    }
  }
  return e.json(200, {
    authenticated: !!uid,
    uid: uid,
    is_platform_admin: isAdmin,
    memberships: memberships,
    ownedTenants: owned,
    probe: probe,
    hint: uid ? "" : "請用 pb.send 並確保已登入（Authorization token）",
  });
});

routerAdd("POST", "/tws/list-members", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  var tenantId = String(data.tenantId || "").trim();
  if (!tenantId) throw new BadRequestError("缺少 tenantId");
  assertCanViewMembers(caller, tenantId);
  var rows = queryRecords("tenant_members", "tenant_id = {:tid}", 200, { tid: tenantId });
  var members = [];
  for (var i = 0; i < rows.length; i++) {
    var uid = recordStr(rows[i], "user_id");
    if (!uid) continue;
    var role = normalizeMemberRole(recordStr(rows[i], "role"));
    if (!role) continue;
    var email = "";
    var displayName = "";
    var createdAt = null;
    var createdByEmail = "";
    var createdByUid = "";
    try {
      var u = twsFindRecordById("users", uid);
      if (u) {
        email = recordStr(u, "email");
        displayName = recordStr(u, "display_name");
        try { createdAt = u.get("created_at"); } catch (e0) { createdAt = null; }
        createdByEmail = recordStr(u, "created_by_email");
        createdByUid = recordStr(u, "created_by_uid");
      }
    } catch (errU) {}
    members.push({
      uid: uid,
      role: role,
      email: email,
      display_name: displayName,
      created_at: createdAt,
      created_by_email: createdByEmail,
      created_by_uid: createdByUid,
    });
  }
  return e.json(200, { tenantId: tenantId, members: members });

}, twsUserAuthMiddleware);

routerAdd("POST", "/tws/create-user", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  var createTenantId = String(data.tenantId || "").trim();
  assertOwnerOrPlatformAdmin(caller, createTenantId);
  var email = String(data.email || "").trim().toLowerCase();
  var password = String(data.password || "");
  if (!email) throw new BadRequestError("請輸入 Email");
  if (password.length < 6) throw new BadRequestError("密碼至少需要 6 個字元");
  var existing = null;
  try { existing = twsFindAuthByEmail("users", email); } catch (errFind) {}
  if (existing) {
    if (!shouldDeleteAuth(existing.id)) throw new BadRequestError("此 Email 已被使用");
    try { twsDelete(existing); } catch (errDel) { throw new BadRequestError("清除舊帳號失敗"); }
  }
  var usersCol = findCollection("users");
  var newUser = new Record(usersCol);
  applyAuthFields(newUser, email, password);
  try { saveAuthRecord(newUser); } catch (errSave) { throw new BadRequestError(mapSaveError(errSave, "建立帳號失敗")); }
  setOptionalUserMeta(newUser, caller, { display_name: data.display_name || "", initial_password: data.initial_password || password });
  return e.json(200, { uid: newUser.id, email: newUser.email() });

}, twsUserAuthMiddleware);

routerAdd("POST", "/tws/upsert-member", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  var tenantId = String(data.tenantId || "").trim();
  var targetUid = String(data.uid || "").trim();
  var role = normalizeMemberRole(data.role || "admin");
  if (!tenantId || !targetUid) throw new BadRequestError("缺少 tenantId 或 uid");
  if (!role) throw new BadRequestError("無效的角色");
  assertOwnerOrPlatformAdmin(caller, tenantId);
  var tenant = loadTenantByKey(tenantId);
  if (!tenant) throw new NotFoundError("找不到專案");
  var ownerRole = getMemberRole(tenantId, targetUid);
  if (ownerRole === "owner" && role !== "owner") {
    throw new BadRequestError("不能變更 Owner 角色");
  }
  var tidEsc = escFilter(tenantId);
  var uidEsc = escFilter(targetUid);
  var existingMember = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tenantId, uid: targetUid })[0] || null;
  if (existingMember) {
    setMemberFields(existingMember, tenantId, tenant, targetUid, role);
    try { twsSave(existingMember); } catch (errUpd) { throw new BadRequestError("更新成員失敗"); }
    return e.json(200, { tenantId: tenantId, uid: targetUid, created: false });
  }
  var membersCol = findCollection("tenant_members");
  var memberRec = new Record(membersCol);
  memberRec.set("created_at", Date.now());
  setMemberFields(memberRec, tenantId, tenant, targetUid, role);
  try { twsSave(memberRec); } catch (errIns) { throw new BadRequestError("新增成員失敗"); }
  return e.json(200, { tenantId: tenantId, uid: targetUid, created: true });

}, twsUserAuthMiddleware);

routerAdd("POST", "/tws/update-member-profile", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  var profileTenantId = String(data.tenantId || "").trim();
  var profileUid = String(data.uid || "").trim();
  if (!profileUid) throw new BadRequestError("缺少 uid");
  if (profileUid !== callerId(caller)) {
    assertOwnerOrPlatformAdmin(caller, profileTenantId);
  }
  var profileUser = twsFindRecordById("users", profileUid);
  if (data.display_name != null) profileUser.set("display_name", String(data.display_name || ""));
  if (data.initial_password != null) profileUser.set("initial_password", String(data.initial_password || ""));
  if (data.created_at != null) profileUser.set("created_at", data.created_at);
  if (data.created_by_uid != null) profileUser.set("created_by_uid", String(data.created_by_uid || ""));
  if (data.created_by_email != null) profileUser.set("created_by_email", String(data.created_by_email || ""));
  try { twsSave(profileUser); } catch (errProf) { throw new BadRequestError("更新用戶資料失敗"); }
  return e.json(200, { uid: profileUid });

}, twsUserAuthMiddleware);

routerAdd("POST", "/tws/remove-member", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  var rmTenantId = String(data.tenantId || "").trim();
  var rmUid = String(data.uid || "").trim();
  if (!rmTenantId || !rmUid) throw new BadRequestError("缺少 tenantId 或 uid");
  if (rmUid === callerId(caller)) throw new BadRequestError("不能移除自己的帳號");
  assertOwnerOrPlatformAdmin(caller, rmTenantId);
  var rmTenant = loadTenantByKey(rmTenantId);
  if (!rmTenant) throw new NotFoundError("找不到專案");
  var rmOwnerRole = getMemberRole(rmTenantId, rmUid);
  if (rmOwnerRole === "owner") throw new BadRequestError("不能移除專案 Owner");
  var rmOwnerUid = recordStr(rmTenant, "owner_uid");
  if (rmOwnerUid && rmUid === rmOwnerUid) throw new BadRequestError("不能移除專案 Owner");
  var tidEsc = escFilter(rmTenantId);
  var uidEsc = escFilter(rmUid);
  var rmMember = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: rmTenantId, uid: rmUid })[0] || null;
  if (!rmMember) throw new NotFoundError("此用戶不在專案成員清單內");
  var rmRole = normalizeMemberRole(recordStr(rmMember, "role"));
  if (!rmRole) throw new NotFoundError("此用戶不在專案成員清單內");
  if (rmRole === "admin") {
    var allMembers = queryRecords("tenant_members", "tenant_id = {:tid}", 200, { tid: rmTenantId });
    if (countAdmins(allMembers) <= 1) throw new BadRequestError("至少需要保留一位後台用戶");
  }
  twsDelete(rmMember);
  var authDeleted = false;
  if (shouldDeleteAuth(rmUid)) {
    try { var orphanUser = twsFindRecordById("users", rmUid); twsDelete(orphanUser); authDeleted = true; }
    catch (errOrphan) { console.error("tws: auth delete skipped:", rmUid, errOrphan); }
  }
  return e.json(200, { tenantId: rmTenantId, uid: rmUid, authDeleted: authDeleted });

}, twsUserAuthMiddleware);

routerAdd("POST", "/tws/set-password", function(e) {
  var escFilter = function(s) {
    return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  };

  var findByField = function(collection, field, value) {
    var v = String(value || "").trim();
    if (!v) return null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findFirstRecordByData === "function") {
        return dao.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err) {}
    try {
      if (typeof $app.findFirstRecordByData === "function") {
        return $app.findFirstRecordByData(collection, field, v) || null;
      }
    } catch (err2) {}
    return null;
  };
  var queryRecords = function(collection, filter, limit, bind) {
    var lim = limit || 500;
    var f = String(filter || "").trim();
    var params = bind || null;
    if (params) {
      try {
        var daoOld = $app.dao();
        if (daoOld && typeof daoOld.findRecordsByFilter === "function") {
          var rowsOld = daoOld.findRecordsByFilter(collection, f, params, lim, 0);
          if (rowsOld && rowsOld.length) return rowsOld;
        }
      } catch (errOld) {}
    }
    try {
      if (typeof $app.findRecordsByFilter === "function") {
        var rowsApp = params
          ? $app.findRecordsByFilter(collection, f, "", lim, 0, params)
          : $app.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsApp && rowsApp.length) return rowsApp;
      }
    } catch (errApp) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordsByFilter === "function") {
        var rowsDao = params
          ? dao.findRecordsByFilter(collection, f, "", lim, 0, params)
          : dao.findRecordsByFilter(collection, f, "", lim, 0);
        if (rowsDao && rowsDao.length) return rowsDao;
      }
    } catch (errDao) {}
    if (lim === 1 && f) {
      try {
        if (typeof $app.findFirstRecordByFilter === "function") {
          var one = $app.findFirstRecordByFilter(collection, f);
          if (one) return [one];
        }
      } catch (errOne) {}
      try {
        var daoOne = $app.dao();
        if (daoOne && typeof daoOne.findFirstRecordByFilter === "function") {
          var one2 = daoOne.findFirstRecordByFilter(collection, f);
          if (one2) return [one2];
        }
      } catch (errOne2) {}
    }
    return [];
  };


  var findCollection = function(name) {
    try {
      if (typeof $app.findCollectionByNameOrId === "function") {
        return $app.findCollectionByNameOrId(name);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findCollectionByNameOrId === "function") {
        return dao.findCollectionByNameOrId(name);
      }
    } catch (err2) {}
    try {
      var dao2 = $app.dao();
      if (dao2 && typeof dao2.findCollectionByName === "function") {
        return dao2.findCollectionByName(name);
      }
    } catch (err3) {}
    throw new BadRequestError("找不到 collection: " + name);
  };
  var twsFindRecordById = function(collection, id) {
    try {
      if (typeof $app.findRecordById === "function") {
        return $app.findRecordById(collection, id);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findRecordById === "function") {
        return dao.findRecordById(collection, id);
      }
    } catch (err2) {}
    return null;
  };
  var twsFindAuthByEmail = function(collection, email) {
    try {
      if (typeof $app.findAuthRecordByEmail === "function") {
        return $app.findAuthRecordByEmail(collection, email);
      }
    } catch (err) {}
    try {
      var dao = $app.dao();
      if (dao && typeof dao.findAuthRecordByEmail === "function") {
        return dao.findAuthRecordByEmail(collection, email);
      }
    } catch (err2) {}
    return null;
  };
  var twsSave = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.saveRecord === "function") {
        dao.saveRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.save === "function") {
        $app.save(record);
        return;
      }
    } catch (err) { lastErr = err; }
    try {
      if (typeof $app.saveNoValidate === "function") {
        $app.saveNoValidate(record);
        return;
      }
    } catch (err2) { lastErr = err2; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "儲存失敗"));
  };
  var deriveUsername = function(email) {
    var em = String(email || "").trim().toLowerCase();
    return em.replace(/@/g, "_").replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_").slice(0, 150) || "tws_user";
  };
  var applyAuthFields = function(record, email, password) {
    var em = String(email || "").trim().toLowerCase();
    var pw = String(password || "");
    var uname = deriveUsername(em);
    try {
      if (typeof record.setEmail === "function") record.setEmail(em);
      else record.set("email", em);
    } catch (errE) { record.set("email", em); }
    try {
      if (typeof record.setUsername === "function") record.setUsername(uname);
      else record.set("username", uname);
    } catch (errU) { try { record.set("username", uname); } catch (errU2) {} }
    try {
      if (typeof record.setPassword === "function") record.setPassword(pw);
      else record.set("password", pw);
    } catch (errP) { record.set("password", pw); }
    try {
      if (typeof record.setVerified === "function") record.setVerified(true);
      else record.set("verified", true);
    } catch (errV) { try { record.set("verified", true); } catch (errV2) {} }
  };
  var twsDelete = function(record) {
    var lastErr = null;
    try {
      var dao = $app.dao();
      if (dao && typeof dao.deleteRecord === "function") {
        dao.deleteRecord(record);
        return;
      }
    } catch (errDao) { lastErr = errDao; }
    try {
      if (typeof $app.delete === "function") {
        $app.delete(record);
        return;
      }
    } catch (err) { lastErr = err; }
    throw new BadRequestError(String((lastErr && lastErr.message) || lastErr || "刪除失敗"));
  };

  var resolveAuth = function(ev) {
    if (ev && ev.auth) return ev.auth;
    try {
      var info = $apis.requestInfo(ev);
      if (info && info.authRecord) return info.authRecord;
    } catch (err) {}
    try {
      if (ev && typeof ev.get === "function") {
        var ar = ev.get("authRecord");
        if (ar) return ar;
      }
    } catch (err2) {}
    try {
      if (ev && typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        if (infoA && infoA.authRecord) return infoA.authRecord;
      }
    } catch (err3) {}
    var token = "";
    try {
      var infoB = $apis.requestInfo(ev);
      var authHdr = (infoB && infoB.headers && (infoB.headers.authorization || infoB.headers.Authorization)) || "";
      if (authHdr) token = String(authHdr).replace(/^Bearer\s+/i, "").trim();
    } catch (err4) {}
    if (token) {
      try {
        if (typeof $app.findAuthRecordByToken === "function") {
          var rec = $app.findAuthRecordByToken(token, "users");
          if (rec) return rec;
        }
      } catch (err5) {}
      try {
        var dao = $app.dao();
        if (dao && typeof dao.findAuthRecordByToken === "function") {
          var rec2 = dao.findAuthRecordByToken(token, "users");
          if (rec2) return rec2;
        }
      } catch (err6) {}
    }
    return null;
  };
  var loadCaller = function(ev) {
    var auth = resolveAuth(ev);
    if (!auth) throw new UnauthorizedError("需要登入");
    try { return twsFindRecordById("users", auth.id); } catch (err) { return auth; }
  };
  var tryParseJson = function(val) {
    if (val && typeof val === "object") return val;
    if (typeof val === "string" && val.trim()) {
      try { return JSON.parse(val); } catch (err) {}
    }
    return null;
  };
  var getJsonBody = function(ev) {
    try {
      var info = $apis.requestInfo(ev);
      var parsed = tryParseJson(info && info.body) || tryParseJson(info && info.data);
      if (parsed) return parsed;
    } catch (err) {}
    try {
      if (typeof ev.requestInfo === "function") {
        var infoA = ev.requestInfo();
        var parsedA = tryParseJson(infoA && infoA.body) || tryParseJson(infoA && infoA.data);
        if (parsedA) return parsedA;
      }
    } catch (err2) {}
    try {
      if (ev.request && ev.request.body && typeof $utils.readerToString === "function") {
        var raw = $utils.readerToString(ev.request.body);
        var parsedC = tryParseJson(raw);
        if (parsedC) return parsedC;
      }
    } catch (err3) {}
    return {};
  };
  var recordBool = function(record, name) {
    try { return record.getBool(name) === true; } catch (err) {
      try { return record.get(name) === true; } catch (err2) { return false; }
    }
  };
  var recordStr = function(record, name) {
    try { return record.getString(name) || ""; } catch (err) {
      try { return String(record.get(name) || ""); } catch (err2) { return ""; }
    }
  };
  var callerId = function(caller) {
    if (!caller) return "";
    if (caller.id) return String(caller.id);
    try { return String(caller.get("id") || ""); } catch (err) { return ""; }
  };
  var normalizeMemberRole = function(val) {
    if (val === "owner") return "owner";
    if (val === true || val === "admin") return "admin";
    if (val === "reception") return "reception";
    return "";
  };
  var getMemberRow = function(tenantKey, uid) {
    var tid = String(tenantKey || "").trim();
    var id = String(uid || "").trim();
    if (!tid || !id) return null;
    var row = queryRecords("tenant_members", "tenant_id = {:tid} && user_id = {:uid}", 1, { tid: tid, uid: id })[0];
    if (row) return row;
    row = findByField("tenant_members", "user_id", id);
    if (row && recordStr(row, "tenant_id") === tid) return row;
    return null;
  };
  var getMemberRole = function(tenantKey, uid) {
    var row = getMemberRow(tenantKey, uid);
    return row ? normalizeMemberRole(recordStr(row, "role")) : "";
  };
  var loadTenantByKey = function(key) {
    var k = String(key || "").trim();
    if (!k) return null;
    var t = findByField("tenants", "tenant_id", k);
    if (t) return t;
    t = findByField("tenants", "slug", k);
    if (t) return t;
    var rows = queryRecords("tenants", "tenant_id = {:k}", 1, { k: k });
    if (rows.length) return rows[0];
    rows = queryRecords("tenants", "slug = {:k}", 1, { k: k });
    return rows.length ? rows[0] : null;
  };
  var listOwnedTenants = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return [];
    var rows = queryRecords("tenant_members", "user_id = {:uid} && role = 'owner'", 50, { uid: id });
    var out = [];
    for (var oi = 0; oi < rows.length; oi++) {
      var tid = recordStr(rows[oi], "tenant_id");
      var tenant = loadTenantByKey(tid);
      out.push({
        tenant_id: tid,
        slug: tenant ? recordStr(tenant, "slug") : tid,
        role: "owner",
      });
    }
    return out;
  };
  var isPlatformAdmin = function(record) { return recordBool(record, "is_platform_admin"); };
  var isTenantOwner = function(tenantId, uid) {
    return getMemberRole(tenantId, uid) === "owner";
  };
  var callerCanManageUsers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return true;
    return isTenantOwner(tenantId, callerId(caller));
  };
  var assertOwnerOrPlatformAdmin = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var tid = String(tenantId || "").trim();
    if (!tid) throw new BadRequestError("缺少 tenantId");
    if (!isTenantOwner(tid, callerId(caller))) {
      throw new ForbiddenError("只有 owner 或平台管理員可以執行此操作");
    }
  };
  var assertCanViewMembers = function(caller, tenantId) {
    if (isPlatformAdmin(caller)) return;
    var role = getMemberRole(tenantId, callerId(caller));
    if (role === "owner" || role === "admin") return;
    throw new ForbiddenError("無權查看成員清單");
  };
  var countAdmins = function(members) {
    var n = 0;
    for (var i = 0; i < members.length; i += 1) {
      var r = normalizeMemberRole(recordStr(members[i], "role"));
      if (r === "admin" || r === "owner") n += 1;
    }
    return n;
  };
  var shouldDeleteAuth = function(uid) {
    var id = String(uid || "").trim();
    if (!id) return false;
    if (findByField("tenant_members", "user_id", id)) return false;
    if (queryRecords("tenant_members", "user_id = {:uid}", 1, { uid: id }).length > 0) return false;
    try {
      var user = twsFindRecordById("users", uid);
      if (user && recordBool(user, "is_platform_admin")) return false;
    } catch (err) { return false; }
    return true;
  };
  var mapSaveError = function(err, fallback) {
    var msg = String((err && err.message) || err || fallback);
    if (msg.indexOf("already in use") >= 0 || msg.indexOf("unique") >= 0) return "此 Email 已被使用";
    return msg || fallback;
  };
  var setMemberFields = function(record, tenantKey, tenantRec, uid, role) {
    record.set("tenant_id", tenantKey);
    record.set("user_id", uid);
    record.set("role", role);
    try { record.set("user", uid); } catch (errU) {}
    try {
      var tid = tenantRec && tenantRec.id ? tenantRec.id : recordStr(tenantRec, "id");
      if (tid) record.set("tenant", tid);
    } catch (errT) {}
  };
  var saveAuthRecord = function(record) {
    twsSave(record);
  };
  var setOptionalUserMeta = function(record, caller, extra) {
    try {
      record.set("is_platform_admin", false);
      record.set("created_at", Date.now());
      record.set("created_by_uid", callerId(caller));
      record.set("created_by_email", recordStr(caller, "email"));
      if (extra && extra.display_name) record.set("display_name", String(extra.display_name));
      if (extra && extra.initial_password) record.set("initial_password", String(extra.initial_password));
      twsSave(record);
    } catch (err) { console.error("tws: optional user meta skipped:", err); }
  };
  var data = getJsonBody(e);
  var caller = loadCaller(e);

  if (!isPlatformAdmin(caller)) throw new ForbiddenError("只限平台管理員");
  var pwUid = String(data.uid || "").trim();
  var newPassword = String(data.newPassword || "");
  if (!pwUid) throw new BadRequestError("缺少 uid");
  if (newPassword.length < 6) throw new BadRequestError("密碼至少需要 6 個字元");
  var pwUser = twsFindRecordById("users", pwUid);
  pwUser.setPassword(newPassword);
  try { saveAuthRecord(pwUser); } catch (errPw) { throw new BadRequestError(mapSaveError(errPw, "重設密碼失敗")); }
  return e.json(200, { uid: pwUid });

}, twsUserAuthMiddleware);

